### ISSUE TITLE
Maven-jar-installer: 'Install' button action fails on Windows

### ISSUE THREAD

**Issue by nrsharan** [javaNoviceProgrammer/Learn-Java-By-Projects#1]
On Windows, using
```java
String command = String.format("mvn install:install-file %s %s %s %s %s", f1, f2, f3, f4, f5) ;
```
did not work. It threw an error:
```
CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:492)
``` 
Modifying the command string to 
```java
String command = String.format("cmd.exe /c mvn install:install-file %s %s %s %s %s", f1, f2, f3, f4, f5) ;
``` 
seems to fix the problem.

**Comment by nrsharan** [comment]
Also, "Install" fails with 
```
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\nrsha\git\repository3\maven-jar-installer\maven-jar-installer\target). Please verify you invoked Maven from the correct directory. -> [Help 1]
```
when "-DgeneratePom=true" is not specified. This happens even when there is a pom.xml file present in the jar that we want to install to the local .m2 repository. Note that the path given above is the location of the executable jar of the maven-jar-installer. 

Thanks for your tutorials, they are really helpful!

**Comment by nrsharan** [comment]
> Also, "Install" fails with
> 
> ```
> [ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\nrsha\git\repository3\maven-jar-installer\maven-jar-installer\target). Please verify you invoked Maven from the correct directory. -> [Help 1]
> ```
> 
> when "-DgeneratePom=true" is not specified. This happens even when there is a pom.xml file present in the jar that we want to install to the local .m2 repository. Note that the path given above is the location of the executable jar of the maven-jar-installer.
> 
> Thanks for your tutorials, they are really helpful!

It works when I use
```
String command = String.format("cmd.exe /c mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file %s, f1);
```
when the 'is Pom' checkbox is checked.
